# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - restore_cache:
          keys:
          - m2-cache-v0.1
      - run: mvn -s .circleci.settings.xml clean install
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: m2-cache-v0.1
          paths:
          - "$HOME/.m2"
  build-docker:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
          - m2-cache-v0.1
      - run: mvn -s .circleci.settings.xml clean install
      - run: docker build -t nhood-org/nhood-engine-service:$CIRCLE_BRANCH .

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - build-docker
