# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

defaults: &defaults
  docker:
    - image: cimg/openjdk:16

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - m2-cache-v0.1
      - run: make build-ci
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: m2-cache-v0.1
          paths:
          - "$HOME/.m2"

  build-docker:
    machine: true
    steps:
      - checkout
      - run: make build-docker-ci

  run-acceptance-tests:
    machine: true
    steps:
      - checkout
      - run: make run-acceptance-tests-ci

  deploy:
    <<: *defaults
    steps:
      - checkout
      - run: make deploy-ci

  release:
    <<: *defaults
    steps:
      - checkout
      - run: make release-ci

  release-docker:
    machine: true
    steps:
      - checkout
      - run: make release-docker-ci

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - build-docker
      - run-acceptance-tests
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
